//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Script/InputSystem/ValidInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ValidInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ValidInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ValidInputs"",
    ""maps"": [
        {
            ""name"": ""EditorInputs"",
            ""id"": ""195c04c2-2619-4540-a444-96b855068909"",
            ""actions"": [
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""9404ed65-c506-4126-a056-ef9a38614ee8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""97fe3647-6781-415b-b72c-f2c2b84ea271"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f385f222-db4f-42e4-9511-18553779f1c3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f361c2df-2041-4fae-ba14-4013562b7bbe"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // EditorInputs
        m_EditorInputs = asset.FindActionMap("EditorInputs", throwIfNotFound: true);
        m_EditorInputs_LeftClick = m_EditorInputs.FindAction("LeftClick", throwIfNotFound: true);
        m_EditorInputs_RightClick = m_EditorInputs.FindAction("RightClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // EditorInputs
    private readonly InputActionMap m_EditorInputs;
    private List<IEditorInputsActions> m_EditorInputsActionsCallbackInterfaces = new List<IEditorInputsActions>();
    private readonly InputAction m_EditorInputs_LeftClick;
    private readonly InputAction m_EditorInputs_RightClick;
    public struct EditorInputsActions
    {
        private @ValidInputs m_Wrapper;
        public EditorInputsActions(@ValidInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftClick => m_Wrapper.m_EditorInputs_LeftClick;
        public InputAction @RightClick => m_Wrapper.m_EditorInputs_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_EditorInputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EditorInputsActions set) { return set.Get(); }
        public void AddCallbacks(IEditorInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_EditorInputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EditorInputsActionsCallbackInterfaces.Add(instance);
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
        }

        private void UnregisterCallbacks(IEditorInputsActions instance)
        {
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
        }

        public void RemoveCallbacks(IEditorInputsActions instance)
        {
            if (m_Wrapper.m_EditorInputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEditorInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_EditorInputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EditorInputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EditorInputsActions @EditorInputs => new EditorInputsActions(this);
    public interface IEditorInputsActions
    {
        void OnLeftClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
    }
}
